### ISSUE TITLE
I am very interested in implementing this project

### ISSUE THREAD

**Issue by vahidalvandi** [components-web-app/components-web-app#42]

**Comment by silverbackdan** [comment]
Hi @vahidalvandi - thanks for raising this issue and sorry for the delay in replying. We have been working hard to get it to a position where it is ready. We will shortly be moving a WIP website https://docs.cwa.rocks to the main domain name https://cwa.rocks. There are a couple of bugs I need to resolve. It's mainly to do with an inconsistency in how the components are stacked, sometimes in the wrong order, for the component manager. I need to do an update whereby there is an indexed store of the components and their children to easily look up whether a newly mounted component is a child of one already mounted. The system in place is sometimes inconsistent. We can then do a little more testing for other bugs and start building some real-world websites with it.

If you are interested in getting involved at all in the development, please reach out. You can see it running using the 'Try it now' link at the main website above.

**Comment by silverbackdan** [comment]
https://cwa.rocks is now launched for the project - if you email directly I can send you a link which will allow you to sign up for more exclusive access to first news and to have your say. For now, I hope you don't mind if I close this issue?
Reach out if there's anything I can do - the documentation will be coming up more soon - you can try it out online - and if you sign up, we will send an email when we think there is a version without bugs we can officially say is an alpha version. Looking like we can get this ready by the end of the year.
